import * as vscode from 'vscode';
import * as path from 'path';
import * as crypto from 'crypto';
import type { ITool, ToolExecutionResult, ChatMode } from './tool.interface';
import { getWorkspaceRoot } from './utils/workspace-utils';

/**
 * PublishFindingsTool - Exclusive to Review Mode
 * 
 * Creates a comprehensive code review report in .echode/codereview/
 * with a unique UUID-based filename for tracking and history.
 */
export class PublishFindingsTool implements ITool {
  name = 'publish_findings';

  private readonly REVIEW_DIR = '.echode/codereview';
  private readonly MAX_CONTENT_SIZE = 1024 * 1024; // 1MB limit for reports

  /**
   * Generate a short UUID for the report filename
   */
  private generateReviewId(): string {
    return crypto.randomUUID().slice(0, 8);
  }

  /**
   * Generate a timestamp string for the report header
   */
  private getTimestamp(): string {
    return new Date().toISOString().replace('T', ' ').slice(0, 19);
  }

  /**
   * Validate that content is proper markdown
   */
  private validateContent(content: string): { valid: boolean; reason?: string } {
    if (!content || content.trim().length === 0) {
      return { valid: false, reason: 'Review content cannot be empty' };
    }

    if (content.length > this.MAX_CONTENT_SIZE) {
      return { 
        valid: false, 
        reason: `Content exceeds ${this.MAX_CONTENT_SIZE / 1024}KB limit` 
      };
    }

    return { valid: true };
  }

  async execute(
    parameters: Record<string, unknown>,
    _onProgress?: unknown,
    _signal?: AbortSignal,
    _mode?: ChatMode
  ): Promise<ToolExecutionResult> {
    const rawContent = parameters.content as string | undefined;
    const title = parameters.title as string | undefined;
    const scope = parameters.scope as string | undefined;

    console.log('[PUBLISH_FINDINGS] ==================== START ====================');

    // Validate content
    if (!rawContent) {
      console.log('[PUBLISH_FINDINGS] ERROR: No content provided');
      return { 
        success: false, 
        error: 'Review content is required. Provide the complete findings in markdown format.' 
      };
    }

    const validation = this.validateContent(rawContent);
    if (!validation.valid) {
      console.log('[PUBLISH_FINDINGS] ERROR:', validation.reason);
      return { success: false, error: validation.reason };
    }

    const workspaceRoot = getWorkspaceRoot();
    if (!workspaceRoot) {
      return { success: false, error: 'No workspace folder open' };
    }

    try {
      // Generate unique review ID and paths
      const reviewId = this.generateReviewId();
      const timestamp = this.getTimestamp();
      const fileName = `review-${reviewId}.md`;
      const reviewDirPath = path.join(workspaceRoot, this.REVIEW_DIR);
      const absolutePath = path.join(reviewDirPath, fileName);
      const relativePath = path.join(this.REVIEW_DIR, fileName);

      // Create directory if it doesn't exist
      const dirUri = vscode.Uri.file(reviewDirPath);
      try {
        await vscode.workspace.fs.createDirectory(dirUri);
        console.log('[PUBLISH_FINDINGS] Created directory:', reviewDirPath);
      } catch {
        // Directory may already exist
      }

      // Build the complete report with metadata header
      const reportTitle = title || 'Code Review Report';
      const scopeInfo = scope ? `**Scope:** ${scope}\n` : '';
      
      const fullContent = `# ${reportTitle}

**Review ID:** \`${reviewId}\`
**Generated:** ${timestamp}
${scopeInfo}
---

${rawContent}

---
*Generated by Echo Code Review*
`;

      // Write the report file
      const uri = vscode.Uri.file(absolutePath);
      const contentBytes = Buffer.from(fullContent, 'utf8');
      await vscode.workspace.fs.writeFile(uri, contentBytes);

      console.log('[PUBLISH_FINDINGS] Report written successfully:', absolutePath);

      // Open the report in markdown preview mode (Ctrl+Shift+V equivalent)
      try {
        await vscode.commands.executeCommand('markdown.showPreview', uri);
        console.log('[PUBLISH_FINDINGS] Report opened in markdown preview');
      } catch (openError) {
        console.warn('[PUBLISH_FINDINGS] Could not open report in preview:', openError);
        // Fallback: try opening in editor if preview fails
        try {
          const doc = await vscode.workspace.openTextDocument(uri);
          await vscode.window.showTextDocument(doc, { 
            preview: true, 
            preserveFocus: true,
            viewColumn: vscode.ViewColumn.Beside
          });
        } catch {
          // Ignore if both fail
        }
      }

      console.log('[PUBLISH_FINDINGS] ==================== SUCCESS ====================');

      return {
        success: true,
        data: {
          // Signal frontend to wait for user action before continuing
          awaitsUserAction: true,
          actionType: 'review_complete',
          message: `Code review published successfully: ${relativePath}`,
          reviewId,
          path: relativePath,
          absolutePath,
          title: reportTitle,
          timestamp,
          lineCount: fullContent.split('\n').length,
          // Include raw content for preview snippet in UI
          reviewContent: rawContent,
          scope,
        },
      };
    } catch (error) {
      console.error('[PUBLISH_FINDINGS] ==================== EXCEPTION ====================');
      console.error('[PUBLISH_FINDINGS] Exception:', error);
      return {
        success: false,
        error: `Failed to publish review: ${error instanceof Error ? error.message : 'Unknown error'}`,
      };
    }
  }
}